clozeapp/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'clozeapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'', include('clozes.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

clozes/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # Course index, ex: /
    url(r'^$', views.index, name='index'),
    # Deck index, ex: /learn/5/
    url(r'^learn/(?P<deck_id>[0-9]+)/$', views.learn, name='learn'),
    # Update chunk (AJAX), ex: /update/504
    url(r'^update/(?P<chunk_id>[0-9]+)/$', views.update, name='update'),
    # Insert new card to deck, ex: /insert/5/
    url(r'^insert/(?P<deck_id>[0-9]+)/$', views.insert, name='insert'),
    # Skip card to get the next one, ex: /insert/24/
    url(r'^skip/(?P<card_id>[0-9]+)/$', views.skip, name='skip'),
    # List cards in deck, ex: /list/5/
    url(r'^list/(?P<deck_id>[0-9]+)/$', views.list, name='list'),
]

clozes/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import date, timedelta
from django.db.models import Min

INITIAL_E_FACTOR = 2500
MIN_E_FACTOR = 1300
E_FACTOR_CHANGE = 200
INTERVALS = [1, 2]


class Course(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField("Image", upload_to="img/", default="img/button_c.png")


class Deck(models.Model):
    course = models.ForeignKey(Course)
    user = models.ForeignKey(User)
    name = models.CharField(max_length=50)

    def next_card(self):
        card_set = self.card_set
        min_next = card_set.aggregate(Min('next_appearance'))['next_appearance__min']
        if min_next > date.today():
            return None
        card_list = card_set.filter(next_appearance__gte=min_next)
        card_list = [card for card in card_list if any(chunk.is_hidden for chunk in card.chunks)]
        if not card_list:
            return None
        return card_list[0]
    
    def add_card(self, card_name, text):
        new_card = Card(id=None, deck=self, name=card_name, next_appearance=date.today())
        new_card.save()
        chunks = text.split("_")
        for i, chunk in enumerate(chunks):
            is_blank = i % 2 == 1
            if is_blank:
                new_chunk = BlankTextChunk(id=None,
                                           next_appearance=date.today(),
                                           e_factor=INITIAL_E_FACTOR)
            else:
                new_chunk = TextChunk(id=None)
            new_chunk.text = chunk
            new_chunk.card = new_card
            new_chunk.index = i
            new_chunk.save()

        new_card.update_next_appearance()

    @property
    def normal_score(self):
        # Get average score of blanks
        blank_scores = []
        for card in self.card_set.all():
            for blank in card.textchunk_set.filter(blanktextchunk__next_appearance__isnull=False):
                blank_scores.append(blank.blanktextchunk.e_factor)
        average = sum(blank_scores, 0.0) / len(blank_scores)
        max_x = max(blank_scores)
        min_x = min(blank_scores)
        MINIMUM_SCORE = 1300
        MAXIMUM_SCORE = 2500
        scaled = [((MAXIMUM_SCORE - MINIMUM_SCORE)*(x - min_x))/(max_x - min_x) + MINIMUM_SCORE for x in blank_scores]
        return average(scaled)


class Card(models.Model):
    deck = models.ForeignKey(Deck)
    name = models.CharField(max_length=50)
    next_appearance = models.DateField()

    def update_next_appearance(self):
        blanks = self.textchunk_set.filter(blanktextchunk__next_appearance__isnull=False)
        self.next_appearance = blanks.aggregate(Min('blanktextchunk__next_appearance')).values()[0]
        if self.next_appearance is None:
            raise ValueError("Card has no blanks")
        self.save()

    def skip(self):
        self.next_appearance = date.today() + timedelta(days=1)

    @property
    def days_left(self):
        self.update_next_appearance()
        d = self.next_appearance - date.today()
        return d.days

    @property
    def chunks(self):
        return self.textchunk_set.order_by('index').all()


class TextChunk(models.Model):
    text = models.TextField()
    card = models.ForeignKey(Card)
    index = models.IntegerField()

    @property
    def is_hidden(self):
        try:
            b = BlankTextChunk.objects.get(pk=self.id)
            return b.next_appearance <= date.today()
        except BlankTextChunk.DoesNotExist:
            return False

    def __str__(self):
        return self.text


class BlankTextChunk(TextChunk):
    next_appearance = models.DateField()
    e_factor = models.IntegerField()
    last_interval = models.IntegerField(default=INTERVALS[0])

    def update_user_feedback(self, user_rating):
        (interval, new_e_factor) = interval_algorithm(self.e_factor, self.last_interval, user_rating)
        self.last_interval = interval
        self.next_appearance += timedelta(interval)
        self.e_factor = new_e_factor
        self.save()
        self.card.update_next_appearance()


def interval_algorithm(e_factor, last_interval, user_rating):
    if user_rating == 0:
        return INTERVALS[0], e_factor
    elif user_rating == 2:
        e_factor = max(MIN_E_FACTOR, e_factor + E_FACTOR_CHANGE)
    return int(round(last_interval * e_factor / 1000)), e_factor


def insert_sample_data():
    # Create user
    sample_user = User.objects.create_user(username='daniel', email='dani@huji.com', password='1234')

    course_names = [u"שפת C", u"היסטוריה עולמית", u"כימיה אורגנית"]
    course_images = ["img/button_c.png", "img/button_history.png", "img/button_chemistry.png"]
    sample_courses = []

    for i, (course_name, course_image) in enumerate(zip(course_names, course_images)):
        sample_course = Course(id=None, name=course_name, image=course_image)
        sample_course.save()
        sample_courses.append(sample_course)

    deck_names = [u"היסטוריה עכשווית", u"המהפכה הצרפתית", u"ימי הביניים", u"העת העתיקה"]
    for i, deck_name in enumerate(deck_names):
        Deck(id=None, course=Course.objects.get(name=u"היסטוריה עולמית"), user=sample_user, name=deck_name).save()

    deck_names = [u"פוינטרים", u"טיפוסי משתנים", u"פונקציות"]
    for i, deck_name in enumerate(deck_names):
        Deck(id=None, course=Course.objects.get(name=u"שפת C"), user=sample_user, name=deck_name).save()

    Deck(id=None, course=Course.objects.get(name=u"כימיה אורגנית"),
         user=sample_user, name=u"מאפייני התכה ורתיחה").save()

    sample_deck = Deck.objects.get(name=u"היסטוריה עכשווית")
    sample_text1 = u"מלחמת העולם _הראשונה_ הסתיימה בשנת 1917"
    sample_deck.add_card(u"מלחמה", sample_text1)
    sample_text2 = u"מלחמת העולם השנייה פרצה בשנת _1939_ ותמה בשנת _1945_"
    sample_deck.add_card(u"מלחמה", sample_text2)

    sample_deck = Deck.objects.get(name=u"פוינטרים")
    for i in range(1, 4):
        load_sample_data_file(i, sample_deck)

    sample_deck = Deck.objects.get(name=u"טיפוסי משתנים")
    load_sample_data_file(4, sample_deck)


def load_sample_data_file(i, sample_deck):
    sample_file = "data/c_sample%d.txt" % i
    with open(sample_file) as f:
        name = f.readline()
        f.readline()
        text = f.readline()
    sample_deck.add_card(name, text)

clozes/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Course, Deck, Card, BlankTextChunk


def index(request):
    course_list = Course.objects.all()
    return render(request, 'clozes/index.html', {'course_list': course_list})


def learn(request, deck_id):
    deck = get_object_or_404(Deck, pk=deck_id)
    card = deck.next_card()
    return render(request, 'clozes/learn.html', {'card': card, 'deck': deck})


def update(request, chunk_id):
    blank = get_object_or_404(BlankTextChunk, pk=chunk_id)
    blank.update_user_feedback(request.GET['rating'])
    return HttpResponse()


def insert(request, deck_id):
    deck = get_object_or_404(Deck, pk=deck_id)
    if request.method == 'POST':
        deck.add_card(request.POST['name'], request.POST['text'])
        return HttpResponseRedirect(reverse('learn', args=(deck_id,)))
    return render(request, 'clozes/insert.html', {'deck': deck})


def skip(request, card_id):
    card = get_object_or_404(Card, pk=card_id)
    card.skip()
    return HttpResponseRedirect(reverse('learn', args=(card.deck.id,)))


def list(request, deck_id):
    deck = get_object_or_404(Deck, pk=deck_id)
    return render(request, 'clozes/list.html', {'deck': deck})

clozes/templates/clozes/index.html
{% load static %}
<html dir="rtl" lang="he">

<head>
    <title>מסך בחירת קורסים</title>

    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="ClozeApp" />
    <meta property="og:image" content="{{ site.domain }}{% static 'img/logo.png' %}" />
    <meta property="og:title" content="ClozeApp" />
    <meta property="og:description" content="Spaced repetition system for course material" />
    <meta property="og:url" content="{{ site.domain }}" />
    <meta property="og:locale" content="he_IL" />

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <script src="{% static 'js/dropdowns-enhancement.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/dropdowns-enhancement.css' %}">


    <style>
        body {
            background: url("{% static 'img/1_no_text_boxes_final.png' %}");
            background-repeat: no-repeat;
            background-size:100%;
            background-size: cover;
        }

        ul li {
            font-size:20px;
            background-color:black;
            color:#FF6600;
        }

        .dropdown-menu {
            background-color:black;
            color:#FF6600;
        }

        h3 {
            color:#FF6600;
        }
    </style>
</head>
<body>

<img src="http://hujihackathon.co.il/images/made%20in%20huji.png">
<img src="{% static 'img/header1.png' %}" width="600" style="padding-right: 10%; padding-top: 5%; padding-bottom: 5%;">

{% if course_list %}
    {% for course in course_list %}
        <dl class="dl-horizontal">
            <div class="btn-group" style="text-align: -webkit-center; display:block; color:#0000FF;">
              <div style="text-align: -webkit-center">
                <div data-toggle="dropdown" class="btn dropdown-toggle" style="color:#0000FF; vertical-align: middle">
                    <img src="{% static course.image.url %}" style="width: 25%; position: relative;"/>
                    <h3 style="font-size: 159%; color:#FF6600;  position: absolute; top: 25%; right: 48%;">{{ course.name }}</h3>
                </div>
                <ul class="dropdown-menu pull-center">
                    {% for deck in course.deck_set.all %}
                      {% if not forloop.first %}
                          <li class="divider"></li>
                      {% endif %}
                      <li class="text-right{% if not deck.card_set.all %} disabled {% endif %}">
                          <a href="{% url 'learn' deck.id %}"><h3>{{ deck.name }} ({{ deck.card_set.count }})</h3></a>
                      </li>
                      <!--(<a href="{% url 'insert' deck.id %}">הכנסת כרטיסיה חדשה</a>)-->
                    {% endfor %}
                </ul>
              </div>
            </div>
        </dl>
    {% endfor %}
{% else %}
    <p>לא נמצאו קורסים.</p>
{% endif %}

</body>
</html>

clozes/templates/clozes/insert.html
<html dir="rtl" lang="he">
<body>

<h1>הכנסת כרטיסיה חדשה לחפיסה {{ deck.name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'insert' deck.id %}" method="post" id="insert-form">
    {% csrf_token %}
    שם הכרטיסיה:
    <input type="text" name="name" />
    <br>
    טקסט (יש לעטוף שדות שתרצו ללמוד בקו תחתון, _):
    <br>
    <textarea id="text" name="text" form="insert-form" rows="30" cols="100"></textarea>
    <br>
    <input type="submit" value="הכנס" />
</form>

</body>
</html>

clozes/templates/clozes/learn.html
{% load static %}

<html dir="rtl" lang="he">
<head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="{% static 'js/cloze_page.js' %}"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/cloze_page_style.css' %}">
</head>
<body>

<section class="course-form">
	<span class="course-tag">שם הקורס:</span>
	<span class="course-entry">{{ deck.course.name }}</span>
	<span class="course-tag" style="margin-right:23%">שם השיעור: </span>
	<span class="course-entry">{{ deck.name }}</span>
 </section>

<section class="cloze-form">
{% if card %}
    <h3>{{ card.name }}</h3>
    {% for chunk in card.chunks %}
        {% if chunk.is_hidden %}
            <span id="{{ chunk.id }}" class="cloze-chunk">{{ chunk.text }}</span>
        {% else %}
            <span class="context">{{ chunk.text }}</span>
        {% endif %}
    {% endfor %}
{% else %}
    אין עוד מה ללמוד היום
{% endif %}
</section>

<nav>
<span style="margin:1%; cursor: pointer">
    <a href="{% url 'index' %}">
        <img src="{% static 'img/buttons2up_dropbox.png' %}" height="60px" width="150px">
    </a>
</span>
<span data-toggle="modal" data-target="#myModal" onclick="on_end_click()" style="margin:1%; cursor: pointer">
    <img src="{% static 'img/buttons2fin_dropbox.png' %}" height="60px" width="150px">
</span>
<!--<a class="btn btn-default"> דלג </a>-->
<!--<a style="cursor: pointer" class="btn-lg btn-success" data-toggle="modal" data-target="#myModal" onclick="on_end_click()">סיימתי!</a>-->
<!--<a href="{% url 'index' %}" class="btn btn-info">קורס אחר</a>-->
</nav>

 <!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">   
      <!-- Modal content-->
      <div class="modal-content">
     
        <div class="modal-body">
			<span style="font-size:10">ציון המבחן: </span>
			<span id="myModal_grade"></span>
            <!--<br>-->
            <!--<span>המבחן יוצג שוב בעוד {{ card.days_left }} ימים</span>-->
        </div>
        <div id="myModal_footer" class="modal-footer">
          <a href="{% url 'index' %}" class="btn-lg btn-info">קורס אחר</a>
          <a href="{% url 'learn' deck.id %}" class="btn-lg btn-success">יאללה עוד אחד!</a>
        </div>
      </div>
      
    </div>
 </div>



</body>
</html>

clozes/templates/clozes/list.html
{% load static %}

<html dir="rtl" lang="he">
<head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="{% static 'js/cloze_page.js' %}"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/cloze_page_style.css' %}">
</head>
<body>

<div class="page-header">
    <h1> ClozeApp </h1>
</div>

{% now "d" as today %}
{{ deck.name }}
{% for card in deck.card_set.all %}
    <section>
        <div>{{ card.name }} (יוצג שוב בעוד {{ card.days_left }} ימים)</div>
        {% for chunk in card.textchunk_set.all %}
            {% if chunk.is_hidden %}
                <span id="{{ chunk.id }}" class="cloze-chunk">{{ chunk.text }}</span>
            {% else %}
                <span class="context">{{ chunk.text }}</span>
            {% endif %}
        {% endfor %}
    </section>
{% endfor %}

</body>
</html>